/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShellEnergy;

import model.Configuration;
import model.Energy.Location;
import model.Energy.RefuelingStation;

import javax.swing.*;
import java.util.ArrayList;

/**
 * @author josephchakola
 */
public class CreateNewEnergyStation extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewEnergyStation
     */
    private final JSplitPane jsp;
    // Variables declaration - do not modify                     
    private javax.swing.JTextField a1Field;
    private javax.swing.JTextField a2Field;
    private javax.swing.JButton back;
    private javax.swing.JCheckBox carwash;
    private javax.swing.JTextField city;
    private javax.swing.JCheckBox ev;
    private javax.swing.JCheckBox foodOptions2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameField;
    private javax.swing.JCheckBox restroom;
    private javax.swing.JButton saveStation;
    private javax.swing.JTextField state;
    private javax.swing.JTextField zip;
    public CreateNewEnergyStation(JSplitPane jsp) {
        initComponents();
        this.jsp = jsp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restroom = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        carwash = new javax.swing.JCheckBox();
        state = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        zip = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        a1Field = new javax.swing.JTextField();
        ev = new javax.swing.JCheckBox();
        foodOptions2 = new javax.swing.JCheckBox();
        a2Field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        saveStation = new javax.swing.JButton();

        restroom.setText("Restrooms");
        restroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restroomActionPerformed(evt);
            }
        });

        jLabel4.setText("Address Line 2");

        jLabel5.setText("City");

        carwash.setText("Car Wash");

        jLabel1.setText("Name");

        jLabel6.setText("State");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Zip");

        ev.setText("EV Charging");
        ev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evActionPerformed(evt);
            }
        });

        foodOptions2.setText("Food Options");
        foodOptions2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodOptions2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Address Line 1");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create New Energy Station");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        saveStation.setText("Save Station");
        saveStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(back))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(243, 243, 243)
                                                .addComponent(saveStation, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(183, 183, 183)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(nameField)
                                                .addComponent(a1Field)
                                                .addComponent(zip, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                                .addComponent(foodOptions2)
                                                .addComponent(carwash)
                                                .addComponent(ev)
                                                .addComponent(restroom)
                                                .addComponent(state)
                                                .addComponent(city)
                                                .addComponent(a2Field))
                                        .addContainerGap(184, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(back)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                                .addComponent(saveStation)
                                .addGap(95, 95, 95))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(a1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(a2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addComponent(ev)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(restroom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(carwash)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(foodOptions2)
                                        .addGap(130, 130, 130)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void restroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restroomActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void evActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evActionPerformed

    private void foodOptions2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodOptions2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodOptions2ActionPerformed

    private void saveStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStationActionPerformed
        // TODO add your handling code here:
        if (nameField.getText().isBlank() || a1Field.getText().isBlank() || a2Field.getText().isBlank() || city.getText().isBlank() || zip.getText().isBlank() || state.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Please fill every field to save.");
        } else {
            ArrayList<String> foodOptions = new ArrayList<>();
            if (foodOptions2.isSelected()) {
                foodOptions.add("Food Options");
            }
            RefuelingStation rs = new RefuelingStation(nameField.getText(),
                    restroom.isSelected(),
                    foodOptions,
                    carwash.isSelected(),
                    ev.isSelected(),
                    new Location(a1Field.getText(), a2Field.getText(), city.getText(), state.getText(), zip.getText()),
                    true);
            Configuration.getRefuelingNetwork().addRefuelingStations(rs);
            JOptionPane.showMessageDialog(this,"Station Saved.");
        }
    }//GEN-LAST:event_saveStationActionPerformed

    private void erase(){
        a1Field.setText("");
        a2Field.setText("");
        city.setText("");
        nameField.setText("");
        state.setText("");
        zip.setText("");
        ev.setSelected(false);
        carwash.setSelected(false);
        foodOptions2.setSelected(false);
        restroom.setSelected(false);
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        EnergyManageFuelStations energy = new EnergyManageFuelStations(jsp);
        jsp.setRightComponent(energy);
    }//GEN-LAST:event_backActionPerformed
    // End of variables declaration                   
}
