/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShellEnergy;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.Configuration;
import model.Energy.Location;
import model.Energy.RefuelingStation;

/**
 *
 * @author josephchakola
 */
public class CreateNewEnergyStations extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewEnergyStations
     */
    private final JSplitPane jsp;
    public CreateNewEnergyStations(JSplitPane jsp) {
        initComponents();
        this.jsp = jsp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        a2Field = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        foodOptions2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        ev = new javax.swing.JCheckBox();
        restroom = new javax.swing.JCheckBox();
        a1Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        zip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        saveStation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        state = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        carwash = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        a2Field1 = new javax.swing.JTextField();
        city1 = new javax.swing.JTextField();
        foodOptions3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        ev1 = new javax.swing.JCheckBox();
        restroom1 = new javax.swing.JCheckBox();
        a1Field1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();
        zip1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        saveStation1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();
        state1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        carwash1 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();

        jLabel5.setText("City");

        foodOptions2.setText("Food Options");
        foodOptions2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodOptions2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Address Line 2");

        ev.setText("EV Charging");
        ev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evActionPerformed(evt);
            }
        });

        restroom.setText("Restrooms");
        restroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restroomActionPerformed(evt);
            }
        });

        jLabel7.setText("Zip");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("State");

        saveStation.setText("Save Station");
        saveStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStationActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create New Energy Station");

        carwash.setText("Car Wash");

        jLabel2.setText("Address Line 1");

        setBackground(new java.awt.Color(255, 255, 244));

        jLabel8.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel8.setText("City");

        a2Field1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N

        city1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N

        foodOptions3.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        foodOptions3.setText("Food Options");
        foodOptions3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodOptions3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel9.setText("Address Line 2");

        ev1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        ev1.setText("EV Charging");
        ev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ev1ActionPerformed(evt);
            }
        });

        restroom1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        restroom1.setText("Restrooms");
        restroom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restroom1ActionPerformed(evt);
            }
        });

        a1Field1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel10.setText("Zip");

        nameField1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        nameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameField1ActionPerformed(evt);
            }
        });

        zip1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel11.setText("State");

        saveStation1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        saveStation1.setText("Save Station");
        saveStation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStation1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel12.setText("Name");

        back1.setText("<");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        state1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        state1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Gill Sans", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Create New Energy Station");

        carwash1.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        carwash1.setText("Car Wash");

        jLabel14.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        jLabel14.setText("Address Line 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveStation1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zip1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carwash1)
                            .addComponent(ev1)
                            .addComponent(foodOptions3)
                            .addComponent(restroom1)
                            .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back1)
                    .addComponent(jLabel13))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a2Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(state1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restroom1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodOptions3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ev1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carwash1)
                .addGap(18, 18, 18)
                .addComponent(saveStation1)
                .addGap(143, 143, 143))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void foodOptions2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodOptions2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodOptions2ActionPerformed

    private void evActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evActionPerformed

    private void restroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restroomActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void saveStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStationActionPerformed
        // TODO add your handling code here:
        if (nameField1.getText().isBlank() || a1Field1.getText().isBlank() || a2Field1.getText().isBlank() || city1.getText().isBlank() || zip1.getText().isBlank() || state1.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Please fill every field to save.");
        } else {
            ArrayList<String> foodOptions = new ArrayList<>();
            if (foodOptions3.isSelected()) {
                foodOptions.add("Food Options");
            }
            RefuelingStation rs = new RefuelingStation(nameField.getText(),
                restroom1.isSelected(),
                foodOptions,
                carwash1.isSelected(),
                ev1.isSelected(),
                new Location(a1Field1.getText(), a2Field1.getText(), city1.getText(), state1.getText(), zip1.getText()),
                true);
            erase();
            Configuration.getRefuelingNetwork().addRefuelingStations(rs);
            JOptionPane.showMessageDialog(this,"Station Saved.");
        }
    }//GEN-LAST:event_saveStationActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        EnergyManageFuelStations energy = new EnergyManageFuelStations(jsp);
        jsp.setRightComponent(energy);
    }//GEN-LAST:event_backActionPerformed

    private void foodOptions3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodOptions3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodOptions3ActionPerformed

    private void ev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ev1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ev1ActionPerformed

    private void restroom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restroom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restroom1ActionPerformed

    private void nameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField1ActionPerformed

    private void saveStation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStation1ActionPerformed
        // TODO add your handling code here:
        if (nameField1.getText().isBlank() || a1Field1.getText().isBlank() || a2Field1.getText().isBlank() || city1.getText().isBlank() || zip1.getText().isBlank() || state1.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Please fill every field to save.");
        } else {
            ArrayList<String> foodOptions = new ArrayList<>();
            if (foodOptions3.isSelected()) {
                foodOptions.add("Food Options");
            }
            RefuelingStation rs = new RefuelingStation(nameField.getText(),
                restroom1.isSelected(),
                foodOptions,
                carwash1.isSelected(),
                ev1.isSelected(),
                new Location(a1Field1.getText(), a2Field1.getText(), city1.getText(), state1.getText(), zip1.getText()),
                true);
            erase();
            Configuration.getRefuelingNetwork().addRefuelingStations(rs);
            JOptionPane.showMessageDialog(this,"Station Saved.");
        }
    }//GEN-LAST:event_saveStation1ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        EnergyManageFuelStations energy = new EnergyManageFuelStations(jsp);
        jsp.setRightComponent(energy);
    }//GEN-LAST:event_back1ActionPerformed

    private void state1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_state1ActionPerformed

 private void erase(){
        a1Field1.setText("");
        a2Field1.setText("");
        city1.setText("");
        nameField1.setText("");
        state1.setText("");
        zip1.setText("");
        ev1.setSelected(false);
        carwash1.setSelected(false);
        foodOptions3.setSelected(false);
        restroom1.setSelected(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1Field;
    private javax.swing.JTextField a1Field1;
    private javax.swing.JTextField a2Field;
    private javax.swing.JTextField a2Field1;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JCheckBox carwash;
    private javax.swing.JCheckBox carwash1;
    private javax.swing.JTextField city;
    private javax.swing.JTextField city1;
    private javax.swing.JCheckBox ev;
    private javax.swing.JCheckBox ev1;
    private javax.swing.JCheckBox foodOptions2;
    private javax.swing.JCheckBox foodOptions3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameField1;
    private javax.swing.JCheckBox restroom;
    private javax.swing.JCheckBox restroom1;
    private javax.swing.JButton saveStation;
    private javax.swing.JButton saveStation1;
    private javax.swing.JTextField state;
    private javax.swing.JTextField state1;
    private javax.swing.JTextField zip;
    private javax.swing.JTextField zip1;
    // End of variables declaration//GEN-END:variables
}
