/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.Configuration;
import model.Role.Person;
import model.Role.RoleManager;
import ui.Finance.FinanceDashboard;
import ui.Finance.InsuranceAdmin;
import ui.FreightCompany.DriverPanel;
import ui.FreightCompany.FreightManageOrders;
import ui.Manufacturing.ManufacturingDashboard;
import ui.ShellEnergy.EnergyAdmin;

/**
 *
 * @author josephchakola
 */
public class LoginPage extends javax.swing.JPanel {

    /**
     * Creates new form LoginPage
     */
    private JSplitPane jsp;
    public LoginPage(JSplitPane jsp) {
        initComponents();
        this.jsp = jsp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jUserName = new javax.swing.JTextField();
        showPass = new javax.swing.JCheckBox();
        jPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 253, 243));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        jLabel1.setText("Transportation");

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jLabel2.setText("....in the age of climate consciousness");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/data/images/How-long-is-a-semi-truck.jpg"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(242, 215, 187));
        jButton1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(129, 106, 87));
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel4.setText("User Name: ");

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel5.setText("Password:");

        jUserName.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserNameActionPerformed(evt);
            }
        });

        showPass.setBackground(new java.awt.Color(255, 255, 255));
        showPass.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });

        jPassword.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(266, 266, 266)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jUserName)
                                    .addComponent(showPass)
                                    .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(344, 344, 344)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPassword)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(showPass)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jPassword.getText().isBlank() || jUserName.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Please fill all fields");
        } else {
            System.out.println("All fields populated");
            Person p = Configuration.getPersonDirectory().getPerson(jUserName.getText());
            System.out.println(p.getRole());
            if(p.getRole().equals(RoleManager.DRIVER)){
               Configuration.getShippingNetwork().getDrivers().stream().filter(d -> d.getDriverName().equals(p.getUsername())).forEach(d -> {
                   System.out.println("Driver found");
                   DriverPanel djp = new DriverPanel(jsp, d);
                   jsp.setRightComponent(djp);
               });

            } else if(p.getRole().equals(RoleManager.BUSINESS_OPS_MANAGER)){
                EnergyAdmin ea = new EnergyAdmin(jsp);
                jsp.setRightComponent(ea);
            } else if(p.getRole().equals(RoleManager.PURCHASE_MANAGER)){
                jsp.setRightComponent(new FinanceDashboard(jsp));
            } else if(p.getRole().equals(RoleManager.SALES_MANAGER)){
                jsp.setRightComponent(new ManufacturingDashboard(jsp));
            } else if(p.getRole().equals(RoleManager.RISK_ANALYST)){
                jsp.setRightComponent(new InsuranceAdmin(jsp));
            } else if(p.getRole().equals(RoleManager.SERVICE_MANAGER)){
                // TODO: Add code to open ServiceManagerJFrame
            } else if(p.getRole().equals(RoleManager.FLEET_MANAGER)){
                FreightManageOrders fmo = new FreightManageOrders(jsp);
                jsp.setRightComponent(fmo);
            }else {
                // TODO: No role found
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserNameActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:
        if(showPass.isSelected()){
            jPassword.setEchoChar((char)0);
        } else {
            jPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUserName;
    private javax.swing.JCheckBox showPass;
    // End of variables declaration//GEN-END:variables
}
